### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by bheemvennapureddy**
Update dependencies

### CODE REVIEW

**Comment by bheemvennapureddy** [comment]
@MaxWaldorf Can we get this in - we are getting errors with tomact and postgres

**Review by MaxWaldorf — COMMENTED** [review]
Sorry, I do not accept PRs to main branch but only the dev one which already is updated...

Also, upgrading PSQL will break any previous installations as major versions of PG are not compatible between eachother...

**Comment by bheemvennapureddy** [comment]
So @MaxWaldorf can we go ahead use the DEV branch to pull the dockerfile and run it ?

**Comment by MaxWaldorf** [comment]
Yes the tag is testing...

**Pull request closed without merging**
